#!/bin/bash
QEMU=/tmp/qemu/bin/qemu-system-loongarch64

BIOS=./2k1000/u-boot-with-spl.bin
DEBUG_UNALIGN=1 DEBUG_GMAC_PHYAD=0 \
$QEMU -M ls2k \
    -rtc base=localtime \
    -serial stdio \
    -serial vc \
    -drive if=pflash,file=$BIOS \
    -m 1024 \
    -device usb-kbd,bus=usb-bus.0 -device usb-tablet,bus=usb-bus.0 \
    -net nic \
    -net user,net=10.0.2.0/24,tftp=/srv/tftp \
    -vnc :0 \
    -D /tmp/qemu.logs \
    -hda ./2k1000/boot.img \
    -hdb ./2k1000/rootfs.img \
    -smp 1
